config/routes.rb
Rails.application.routes.draw do
  
  resources :users, only: [:edit]
  resource :profile,only: [:show,:edit, :update]

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :rooms
  resources :reservations
  post 'reservations/confirm', to: 'reservations#confirm'
  
  devise_for :users
  root 'home#index' 
  get 'home/index'
  
  get '/users/account' => 'users#account'
  
  get "search",to: 'rooms#search'
  get "searcharea",to: 'rooms#searcharea'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :check_in, presence: true
  validates :check_out, presence: true
  validates :people, presence: true

  def sum_of_reserve_price
    (check_out - check_in) / 86400 * room.price * people 
  end
  
  def sum_of_day
    (check_out - check_in).to_i / 1.day
  end

end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :reservations, dependent: :destroy
  
  validates :roomname, presence: true
  validates :roominfo, presence: true
  validates :price, presence: true ,numericality: {only_integer: true, greater_than_or_equal_to: 1}
  validates :address, presence: true

  mount_uploader :roomimage, RoomimageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :rooms 
  has_many :reservations  
  
  validates :username, presence: true

  mount_uploader :avatar, AvatarUploader
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
  
    
    before_action :configure_permitted_parameters, if: :devise_controller?
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username]) 
    end
 end
  
  

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
  end
  
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_user,only: %i[edit update]

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to profile_path
    end
  end

  private
  def set_user
    @user = User.find(current_user.id)
  end

  def user_params
    params.require(:user).permit(:email,:username,:profile,:avatar)
  end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def index
    @user = current_user
    @reservations = current_user.reservations
  end
  
  def new
    @reservation = Reservation.new
  end

  def confirm
    @reservation = Reservation.new(reservation_params)
    
    if @reservation.check_in.blank? || @reservation.check_out.blank? || @reservation.people.blank? 
      flash[:alert] = "全ての入力欄に入力を行ってください。"
      redirect_to request.referer
    elsif @reservation.check_out < @reservation.check_in
      flash[:alert] = "チェックイン日時はチェックアウト日時以降の日付にしてください。"
      redirect_to request.referer
    elsif @reservation.people < 1
      flash[:alert] = "0以下の数値は入力できません"
      redirect_to request.referer
    end
  end
  
  def create
    @reservation = Reservation.new(reservation_params)
    @reservation.user_id = current_user.id
    if @reservation.save
      redirect_to  :reservations, notice:"予約完了しました！"
    else 
      @room = Room.find(params[:id])
      render 'rooms/show'
    end  
  end  

  
  def destroy
    @reservation = Reservation.find(params[:room_id])
    @reservation.destroy
  end 
  
  private
  def reservation_params
    params.require(:reservation).permit(:user_id,:room_id,:check_in,:check_out,:people)
  end
  
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  
  def index
    @rooms = current_user.rooms
  end

  def show
    @room = Room.find(params[:id])
    @reservation = Reservation.new
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    @room.user_id = current_user.id
    if @room.save
      flash[:notice] = "施設情報を登録しました"
      redirect_to :rooms
    else
      flash[:alert] = "施設情報を登録できませんでした"
      redirect_to request.referer
    end
  end

  def edit
    @room = Room.find(params[:id])
  end

  def update
    @room = Room.find(params[:id])
    @room.update(room_params)
    redirect_to :rooms
  end  

  def destroy
    @rooms = Room.find(params[:id])
    @rooms.destroy
    redirect_to :rooms
  end 

  def search
    search_word  = params[:word]
    @rooms = Room.where("roomname LIKE ? or roominfo LIKE ?  " ,"%#{search_word}%","%#{search_word}%")
  end

  def searcharea
    search_word  = params[:word]
    @rooms = Room.where("address LIKE ?","%#{search_word }%")
  end  

  private
  def room_params
    params.require(:room).permit(:roomname,:roominfo,:price,:address,:roomimage)
  end  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def account
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/rooms/searches_helper.rb
module Rooms::SearchesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>エリア検索</h1>
<div class="search_form">
    <%= form_with url: searcharea_path, local: true, method: :get do |f| %>
      <%= f.text_field :word,placeholder:"エリア名を入力" %>
      <%= f.submit "検索", class: "btn btn-primary" %>
    <% end %>
  </div>

<h2>おすすめのエリア</h2>
<a href="/searcharea?word=東京&commit=検索"><%= image_tag "Tokyo_image.png", size: "600x400" %></a>
<a href="/searcharea?word=大阪&commit=検索"><%= image_tag "Osaka_image.png", size: "600x400" %></a></a>
<a href="/searcharea?word=京都&commit=検索"><%= image_tag "Kyoto_image.png", size: "600x400" %></a></a>
<a href="/searcharea?word=札幌&commit=検索"><%= image_tag "Sapporo_image.png", size: "600x400" %></a></a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <title>ReservationApp</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

  <body>
    <header class="header01">
    <%= link_to root_path, class: "navbar-item" do %>
    <h1>ReservationApp</h1> 
    <% end %>
    <nav class="header01-nav">
      <ul class="header01-list">
        <li>
          <% if user_signed_in? %>
          <div class="dropdown">
            <input id="tg" class="dropInput" type="checkbox">
            <label for="tg" class="dropLabel"><%= image_tag current_user.avatar.url, class: 'rounded-circle', size: '50x50' %><%= current_user.username %></label>
            <ul class="menu animation">
              <li><a href="/profile">アカウント設定</a></li>
              <li><%= link_to "新規部屋登録", new_room_path, class: 'get' %></li>
              <li><%= link_to "登録済み部屋一覧", rooms_path, class: 'get' %></li>
              <li><%= link_to "予約済み一覧", reservations_path, class: 'get' %></li>
              <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
            </ul>
          </div>
        </li>
        <% else %>
         <li><%= link_to "ログイン", new_user_session_path, class: 'post' %></li>
         <li><%= link_to "新規登録", new_user_registration_path, class: 'post' %></li>
      <% end %>
    </header>
    <%= yield %>
  </body>
</html>

app/views/profiles/edit.html.erb
<%= form_with model: @user, url: profile_path, local: true do |f| %>
  <div class="field">
    <%= f.label :ユーザー名 %>
    <%= f.text_field :username, class: 'form-control mb-3' %>
  </div>

  <div class="field">
    <%= f.label :自己紹介 %><br />
    <%= f.text_area :profile, class: 'form-control mb-3' %>
  </div  
  <div class="field">
    <%= f.label :アバターアイコン %>
    <%= f.file_field :avatar,class: 'form-control mb-3' %>
    <%= f.hidden_field :avatar_cache %>
  </div>
  <%= link_to "戻る", :back %>
  <%= f.submit "更新", class: "btn btn-primary"%>
<%end%>
 

app/views/profiles/show.html.erb
<h1>プロフィール</h1>

<a href="/profile/edit">編集</a>
<table class="table">
  <tr>
    <th scope="row"><%= t(User.human_attribute_name(:ユーザー名)) %></th>
    <td><%= current_user.username %></td>
  </tr>
  <tr>
    <th scope="row"><%= t(User.human_attribute_name(:自己紹介)) %></th>
    <td><%= current_user.profile %></td>
  </tr>
  <tr>
    <th scope="row"><%= t(User.human_attribute_name(:アバターアイコン)) %></th>
    <td><%= image_tag current_user.avatar.url, class: 'rounded-circle', size: '50x50' %></td>
  </tr>
</table>
      
     
<a href="/users/account">アカウント情報</a>       

     

app/views/reservations/confirm.html.erb
<h1>予約内容確認</h1>

<p>合計宿泊費</p>
<td><%= @reservation.sum_of_reserve_price.to_i %>円</td>
<p>チェックイン日時</p>
<td><%= @reservation.check_in.strftime('%Y/%m/%d') %></td>
<p>チェックアウト日時</p>
<td><%= @reservation.check_out.strftime('%Y/%m/%d') %></td>
<p>宿泊人数</p>
<td><%= @reservation.people %>人</td>
<p>宿泊日数</p>
<td><%= @reservation.sum_of_day %>日</td>



<p class="ReservationConfirm">上記内容で正しければ「確定」ボタンを押してください。</p>
  <%= form_with model: @reservation, method: :post do |f| %>
    <%= f.hidden_field :check_in %>
    <%= f.hidden_field :check_out %>
    <%= f.hidden_field :sum_of_day %>
    <%= f.hidden_field :people %>
    <%= f.hidden_field :sum_of_reserve_price %>
    <%= f.hidden_field :user_id %>
    <%= f.hidden_field :room_id %>
    <input type="submit" name="commit" value="予約を確定" class="btn ReservationConfirm__button">
<% end %>

<%= link_to "戻る", :back %>

app/views/reservations/index.html.erb
<%= notice %>

<h1>予約一覧</h1>
<table>
   <thead>
     <tr>
       <th>画像</th>
       <th>施設名</th>
       <th>紹介文</th>
       <th>合計宿泊費</th>
       <th>チェックイン日</th>
       <th>チェックアウト日</th>
       <th>予約確定日時</th>
     </tr>
   </thead>
 
   <tbody>
       <% @reservations.each do |reservation| %>
        <td>
        <% if reservation.room.roomimage.present? %>
        <%= image_tag reservation.room.roomimage.to_s, size: "150x100" %>
        <% else %>
        <%= image_tag "default_room.png", size: "150x100" %>
        </td>
        <% end %>
         <td><%= reservation.room.roomname %></td>
         <td><%= reservation.room.roominfo %></td>
         <td><%= reservation.sum_of_reserve_price.to_i %>円</td>
         <td><%= reservation.check_in.strftime('%Y/%m/%d') %></td>
         <td><%= reservation.check_out.strftime('%Y/%m/%d') %></td>
         <td><%= reservation.created_at.to_s(:datetime_jp) %></td>
       </tr>
       <% end %>
   </tbody>
 </table>
 

app/views/rooms/edit.html.erb
<h1>施設情報の編集</h1>

<%= form_for @room do |f| %>
<%= f.label :施設名 %>
<%= f.text_field :roomname %><br>

<%= f.label :施設詳細 %>
<%= f.text_area :roominfo %><br>

<%= f.label :料金 %>
<%= f.text_field :price %><br>

<%= f.label :住所 %>
<%= f.text_field :address %><br>
    
<%= f.submit  "更新", class: "btn btn-primary" %>
<%= link_to "戻る", :back %>
<% end %>    

app/views/rooms/index.html.erb
<h1>フリーワード検索</h1>
<div class="search_form">
    <%= form_with url: search_path, local: true, method: :get do |f| %>
    <%= f.text_field :word,placeholder:"キーワードを入力" %>
    <%= f.submit "検索", class: "btn btn-primary" %>
  <% end %>
</div>

<h1>エリア検索</h1>
<div class="searcharea_form">
  <%= form_with url: searcharea_path, local: true, method: :get do |f| %>
    <%= f.text_field :word,placeholder:"エリア名を入力" %>
    <%= f.submit "検索", class: "btn btn-primary" %>
  <% end %>
</div>

<%= flash[:notice] %>

<h1>登録済み一覧</h1>
<table>
  <thead>
    <tr>
      <th>画像</th>
      <th>施設名</th>
      <th>紹介文</th>
      <th>宿泊費/日</th>
      <th>作成日</th>
      <th>編集</th>
      <th>削除</th>
    </tr>
  </thead>

  <tbody>
  <% @rooms.each do |room| %>
    <tr>
      <td>
      <% if room.roomimage.present? %>
      <%= image_tag room.roomimage.to_s, size: "150x100" %>
      <% else %>
      <%= image_tag "default_room.png", size: "150x100" %>
      <% end %></td>
    
      <td><%= link_to room.roomname, room_path(room) %></td>
      <td><%= room.roominfo %></td>
      <td><%= room.price %>円/日</td>
      <td><%= room.created_at.strftime('%Y/%m/%d') %></td>
      <td><%= link_to '編集',edit_room_path(room)%></td>
      <td><%= button_to "削除",room, method: :delete,data: { turbo_method: 'delete' }%></td>
    </tr>  
    <% end %>
  </tbody>
</table>
  

      
      
      
      
  

app/views/rooms/new.html.erb
<h1>新規登録</h1>
<%= flash[:alert] %>
<%= form_for @room do |f| %>
<%= f.label :施設名 %>
<%= f.text_field :roomname %><br>

<%= f.label :紹介文 %>
<%= f.text_area :roominfo %><br>

<%= f.label :宿泊費 %>
<%= f.text_field :price %><br>

<%= f.label :住所 %>
<%= f.text_field :address %><br>

<div class="field">
  <%= f.label :部屋画像 %>
  <%= f.file_field :roomimage %>
</div>


<%= f.submit "新規登録", class: "btn btn-primary"%>
<% end %>

app/views/rooms/search.html.erb
<%= @rooms.count %>件見つかりました。

<h1>登録済み一覧</h1>
<table>
  <thead>
    <tr>
      <th>画像</th>
      <th>施設名</th>
      <th>紹介文</th>
      <th>住所</th>
      <th>宿泊費/日</th>
      <th>詳細</th>
    </tr>
  </thead>

  <tbody>
  <% @rooms.each do |room| %>
    <tr>
      <td>
      <% if room.roomimage.present? %>
      <%= image_tag room.roomimage.to_s, size: "150x100" %>
      <% else %>
      <%= image_tag "default_room.png", size: "150x100" %>
      <% end %></td>
      <td><%= room.roomname %></td>
      <td><%= room.roominfo %></td>
      <td><%= room.address %></td>
      <td><%= room.price %>円</td>
      <td><%= link_to '詳細',room_path(room)%></td>
    </tr>  
    <% end %>
  </tbody>
</table>
  

      
      
      
      
  

app/views/rooms/searcharea.html.erb
<%= @rooms.count %>件見つかりました。

<h1>登録済み一覧</h1>
<table>
  <thead>
    <tr>
      <th>画像</th>
      <th>施設名</th>
      <th>紹介文</th>
      <th>住所</th>
      <th>宿泊費/日</th>
      <th>詳細</th>
    </tr>
  </thead>

  <tbody>
  <% @rooms.each do |room| %>
    <tr>
      <td>
      <% if room.roomimage.present? %>
      <%= image_tag room.roomimage.to_s, size: "150x100" %>
      <% else %>
      <%= image_tag "default_room.png", size: "150x100" %>
      <% end %></td>
      <td><%= room.roomname %></td>
      <td><%= room.roominfo %></td>
      <td><%= room.address %></td>
      <td><%= room.price %>円</td>
      <td><%= link_to '詳細',room_path(room)%></td>
    </tr>  
    <% end %>
  </tbody>
</table>

app/views/rooms/show.html.erb
<h1>施設詳細</h1>

<% if @room.roomimage? %>  <!-- アップロード画像がある場合に実行する -->
<%= image_tag @room.roomimage.url, :size => '600x450' %><!-- roomインスタンスの画像ファイルのURLを取得し表示 -->
<% else %>  
<%= image_tag "/assets/default_room.png", :size => '600x450',:class=>"profile-img" %>
<% end %>

<div class="RoomTextContainer">
  <div class="RoomDetailsBody_name-and-price">
    <p class="Details-name"><%= @room.roomname %></p>
    <p class="Details-price">¥<%= @room.price %>〜</p>
  </div>
  <div>
    <p class="Details-address"><%= @room.address %></p>
  </div>
  <div>
    <p class="Details-info"><%= @room.roominfo %></p>
  </div>
</div>  



<%= form_with model: @reservation, method: :post, url: reservations_confirm_path  ,local: true do |f| %>
  <div class="reserve_form">
    <%= flash[:alert] %>
      <div>
        <%= f.label :チェックイン %>
        <%= f.date_field :check_in,min: Time.zone.now %>
      </div>
      <div>
        <%= f.label :チェックアウト %>
        <%= f.date_field :check_out,min: Time.zone.tomorrow %>
      </div>
      <div>
        <%= f.label :人数 %>
        <%= f.text_field :people %>
      </div>
      <%= f.hidden_field :room_id ,value: @room.id %>
      <%= f.hidden_field :roomname %>
      <%= f.hidden_field :roominfo %>
      <%= f.hidden_field :price %>
      <%= f.hidden_field :address %>
      <%= f.submit '予約する' %>
      <%= link_to "戻る", :back %>
  </div>    
    
<% end %>

app/views/users/account.html.erb
<h1>アカウント</h1>

<a href="/users/edit">編集</a>
<h4> メールアドレス： <%= current_user.email %> </h4>
<h4> パスワード: ********* </h4>

<a href="/profile">プロフィール</a>

app/views/users/edit.html.erb
<%= form_with model: @user, url: user_registration_path, local: true do |f| %>
  
  <div class="field">
    <%= f.label :メールアドレス %>
    <%= f.email_field :email, class: 'form-control mb-3' %>
  </div>
  <%= f.submit "更新", class: "btn btn-primary"%>
<%end%>